----------------- RESOLUÇÃO DOS EXERCICIOS DA BIBLIOTECA UTILIZANDO JOIN

-----------------7

SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.ANO_PUBLICACAO, EDITORA.NOME as 'EDITORA', CATEGORIA.TIPO_CATEGORIA AS 'CATEGORIA'
FROM LIVRO
INNER JOIN EDITORA ON EDITORA.ID = LIVRO.FK_EDITORA
INNER JOIN CATEGORIA ON CATEGORIA.ID = LIVRO.FK_CATEGORIA
ORDER BY LIVRO.TITULO;

---------------- 8

SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.ANO_PUBLICACAO, EDITORA.NOME AS 'EDITORA', CATEGORIA.TIPO_CATEGORIA AS 'CATEGORIA', AUTOR.NOME AS 'AUTOR'
FROM LIVRO
INNER JOIN EDITORA ON EDITORA.ID = LIVRO.FK_EDITORA
INNER JOIN CATEGORIA ON CATEGORIA.ID = LIVRO.FK_CATEGORIA
INNER JOIN LIVROAUTOR ON LIVROAUTOR.FK_LIVRO = LIVRO.ISBN
INNER JOIN AUTOR ON AUTOR.ID = LIVROAUTOR.FK_AUTOR
ORDER BY AUTOR.NOME;
---------------- 9
-- crie uma consulta utilizando join para relacionar todos os dados disponíveis dos livros da categoria de literatura juvenil em ordem de ano
SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.ANO_PUBLICACAO, EDITORA.NOME AS 'EDITORA', CATEGORIA.TIPO_CATEGORIA AS 'CATEGORIA', AUTOR.NOME AS 'AUTOR'
FROM LIVRO
INNER JOIN EDITORA ON EDITORA.ID = LIVRO.FK_EDITORA
INNER JOIN CATEGORIA ON CATEGORIA.ID = LIVRO.FK_CATEGORIA
INNER JOIN LIVROAUTOR ON LIVROAUTOR.FK_LIVRO = LIVRO.ISBN
INNER JOIN AUTOR ON AUTOR.ID = LIVROAUTOR.FK_AUTOR
WHERE CATEGORIA.TIPO_CATEGORIA LIKE '%Juvenil%'
ORDER BY LIVRO.ANO_PUBLICACAO ASC;

---------------- 10
-- crie uma consulta utilizando join para relacionar todos os dados disponíveis dos livros de humor ou ficção científica com ano entre 2000 e 2010
SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.ANO_PUBLICACAO, EDITORA.NOME AS 'EDITORA', CATEGORIA.TIPO_CATEGORIA AS 'CATEGORIA', AUTOR.NOME AS 'Autor'
FROM LIVRO
JOIN EDITORA ON LIVRO.FK_EDITORA = EDITORA.ID
JOIN CATEGORIA ON LIVRO.FK_CATEGORIA = CATEGORIA.ID
JOIN LIVROAUTOR ON LIVRO.ISBN = LIVROAUTOR.FK_LIVRO
JOIN AUTOR ON LIVROAUTOR.FK_AUTOR = AUTOR.ID
WHERE CATEGORIA.TIPO_CATEGORIA LIKE '%humor%' OR CATEGORIA.TIPO_CATEGORIA LIKE '%fic%fica'
  AND YEAR(LIVRO.ANO_PUBLICACAO) BETWEEN 2000 AND 2010;