CREATE DATABASE CatalogoDinossauros

CREATE TABLE grupo
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(250) NOT NULL
);

CREATE TABLE era
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(250) NOT NULL
);

CREATE TABLE pais
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(250) NOT NULL
);

CREATE TABLE descobridor
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(150) NOT NULL,
	fk_pais INTEGER NOT NULL,
	FOREIGN KEY (fk_pais) REFERENCES pais(id)
);

CREATE TABLE dinossauro
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	especie VARCHAR(250) NOT NULL,
	toneladas INTEGER NOT NULL,
	ano_descoberta INTEGER NOT NULL,
	inicio INTEGER NOT NULL,
	fim INTEGER NOT NULL,
	fk_descobridor INTEGER NOT NULL,
	fk_grupo INTEGER NOT NULL,
	fk_era INTEGER NOT NULL,
	fk_pais INTEGER NOT NULL,
	FOREIGN KEY (fk_descobridor) REFERENCES descobridor(id),
	FOREIGN KEY (fk_grupo) REFERENCES grupo(id),
	FOREIGN KEY (fk_era) REFERENCES era(id),
	FOREIGN KEY (fk_pais) REFERENCES pais(id)
)

